// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using advanced_jobmatchingtool_webapp.Models;

#nullable disable

namespace advanced_jobmatchingtool_webapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260304215233_Aanpassing-Statuut")]
    partial class AanpassingStatuut
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.AntwoordKandidaat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AntwoordTekst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Categorie")
                        .HasColumnType("text");

                    b.Property<DateTime>("DatumIngevuld")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtraInfo")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VraagKandidaatId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VraagKandidaatId");

                    b.ToTable("AntwoordenKandidaten");
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.AntwoordKlant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AntwoordTekst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Categorie")
                        .HasColumnType("text");

                    b.Property<DateTime>("DatumIngevuld")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtraInfo")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VraagKlantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VraagKlantId");

                    b.ToTable("AntwoordenKlanten");
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.AntwoordOptie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OptieTekst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AntwoordOpties");
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Familienaam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("ProfileComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TermsCond")
                        .HasColumnType("boolean");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.CategorieSubCat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NaamCategorie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NaamSubCategorie")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CategorieSubCats");
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.PersonaliaKandidaat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gsmnr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telnr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Personalia");
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.Prospect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Btwnr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gsmnr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NaamContactpersoon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NaamOnderneming")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OmschrijvingOnderneming")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefoonnr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TermsCond")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Prospecten");
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.StatuutKandidaat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diagnose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HeeftIMWStatuut")
                        .HasColumnType("boolean");

                    b.Property<bool>("HulpNodigBijInvullen")
                        .HasColumnType("boolean");

                    b.Property<string>("IMWStatuutBestand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IMWStatuutBestandOrigineleNaam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Statuten");
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.VraagKandidaat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AntwoordOptieId")
                        .HasColumnType("integer");

                    b.Property<int>("CategorieSubCatId")
                        .HasColumnType("integer");

                    b.Property<int>("SoortAntwoord")
                        .HasColumnType("integer");

                    b.Property<string>("VraagText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AntwoordOptieId");

                    b.HasIndex("CategorieSubCatId");

                    b.ToTable("VragenKandidaten");
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.VraagKlant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AntwoordOptieId")
                        .HasColumnType("integer");

                    b.Property<int>("CategorieSubCatId")
                        .HasColumnType("integer");

                    b.Property<int>("SoortAntwoord")
                        .HasColumnType("integer");

                    b.Property<string>("VraagText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AntwoordOptieId");

                    b.HasIndex("CategorieSubCatId");

                    b.ToTable("VragenKlanten");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("advanced_jobmatchingtool_webapp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("advanced_jobmatchingtool_webapp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("advanced_jobmatchingtool_webapp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("advanced_jobmatchingtool_webapp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.AntwoordKandidaat", b =>
                {
                    b.HasOne("advanced_jobmatchingtool_webapp.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("advanced_jobmatchingtool_webapp.Models.VraagKandidaat", "VraagKandidaat")
                        .WithMany("AntwoordenKandidaten")
                        .HasForeignKey("VraagKandidaatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VraagKandidaat");
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.AntwoordKlant", b =>
                {
                    b.HasOne("advanced_jobmatchingtool_webapp.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("advanced_jobmatchingtool_webapp.Models.VraagKlant", "VraagKlant")
                        .WithMany("AntwoordenKlanten")
                        .HasForeignKey("VraagKlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VraagKlant");
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.PersonaliaKandidaat", b =>
                {
                    b.HasOne("advanced_jobmatchingtool_webapp.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Personalia")
                        .HasForeignKey("advanced_jobmatchingtool_webapp.Models.PersonaliaKandidaat", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.StatuutKandidaat", b =>
                {
                    b.HasOne("advanced_jobmatchingtool_webapp.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Statuut")
                        .HasForeignKey("advanced_jobmatchingtool_webapp.Models.StatuutKandidaat", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.VraagKandidaat", b =>
                {
                    b.HasOne("advanced_jobmatchingtool_webapp.Models.AntwoordOptie", "AntwoordOptie")
                        .WithMany("VragenKandidaten")
                        .HasForeignKey("AntwoordOptieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("advanced_jobmatchingtool_webapp.Models.CategorieSubCat", "Categorie")
                        .WithMany("VragenKandidaten")
                        .HasForeignKey("CategorieSubCatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AntwoordOptie");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.VraagKlant", b =>
                {
                    b.HasOne("advanced_jobmatchingtool_webapp.Models.AntwoordOptie", "AntwoordOptie")
                        .WithMany("VragenKlanten")
                        .HasForeignKey("AntwoordOptieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("advanced_jobmatchingtool_webapp.Models.CategorieSubCat", "Categorie")
                        .WithMany("VragenKlanten")
                        .HasForeignKey("CategorieSubCatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AntwoordOptie");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.AntwoordOptie", b =>
                {
                    b.Navigation("VragenKandidaten");

                    b.Navigation("VragenKlanten");
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.ApplicationUser", b =>
                {
                    b.Navigation("Personalia")
                        .IsRequired();

                    b.Navigation("Statuut")
                        .IsRequired();
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.CategorieSubCat", b =>
                {
                    b.Navigation("VragenKandidaten");

                    b.Navigation("VragenKlanten");
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.VraagKandidaat", b =>
                {
                    b.Navigation("AntwoordenKandidaten");
                });

            modelBuilder.Entity("advanced_jobmatchingtool_webapp.Models.VraagKlant", b =>
                {
                    b.Navigation("AntwoordenKlanten");
                });
#pragma warning restore 612, 618
        }
    }
}
